[package]
name = "serde_stacker"
version = "0.0.0"
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT OR Apache-2.0"
description = "Serde adapter that avoids stack overflow by dynamically growing the stack"
edition = "2018"

[dependencies]
serde = "1.0"

[dev-dependencies]
serde_json = { version = "1.0", features = ["unbounded_depth"] }
